spring:
  application:
    name: ola-maps-consumer
  config:
    import: classpath:application-secrets.yml
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: ${secrets.client-id}
            client-secret: ${secrets.client-secret}
            authorization-grant-type: client_credentials
            scope: openid
            provider: my-provider
        provider:
          my-provider:
            token-uri: https://account.olamaps.io/realms/olamaps/protocol/openid-connect/token

server:
  port: 8090

resilience4j:
  circuitbreaker:
    instances:
      breaker:
        registerHealthIndicator: true
        sliding-window-size: 100
        sliding-window-type: count_based
        permitted-number-of-calls-in-half-open-state: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state:
          seconds: 30
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
  retry:
    instances:
      try:
        max-attempts: 3
        wait-duration:
          seconds: 3



